### ISSUE TITLE
Prompt interrupt not catched

### ISSUE THREAD

**Issue by denouche** [manifoldco/promptui#102]
Hello,
When I use the basic prompt the Ctrl-C interrupt is never catched, and the error is never throwed.
I found the origin of the bug, I will make a PR.

**Comment by ItalyPaleAle** [comment]
I am still having issues. When there's a prompt, pressing CTRL+C doesn't interrupt the application.

**Comment by richardzcode** [comment]
In case anybody wondered. When CTRL+C pressed you'll get an err. Just need to check it. It is pretty obvious but developers new to promptui and go may scratch their head for some minutes.

**Comment by thiskevinwang** [comment]
@richardzcode I'm a developer new to promptui and I'm scratching my head 😅 — do you have an example of how to catch <kbd>Ctrl + C</kbd> in `promptui`?
