### ISSUE TITLE
captures ctrl + z

### ISSUE THREAD

**Issue by cg831344** [manifoldco/promptui#109]
Is it possible to increase the signal SIGTSTP that captures ctrl + z, sorry m my English is not very good

**Comment by alexanderhansen** [comment]
This works for me:


```go
i, _, err := prompt.Run()
if err != nil && err.Error() == "^C" {
  // Gracefully handle abort
  return
}
```

**Comment by hitzhangjie** [comment]
Should we print output error message of validateFunc when captures ctrl+z?

It's weired. sometimes it output the validate error message, sometimes not.

**Comment by cg831344** [comment]
> This works for me:
> 
> ```go
> i, _, err := prompt.Run()
> if err != nil && err.Error() == "^C" {
>   // Gracefully handle abort
>   return
> }
> ```

**Comment by cg831344** [comment]
think you
