### ISSUE TITLE
go mod fails to pull dependencies for promptui

### ISSUE THREAD

**Issue by jpninanjohn** [manifoldco/promptui#115]
Getting this error when trying to import promptui using go mod.

```
github.com/manifoldco/promptui imports
	github.com/alecthomas/gometalinter imports
	gopkg.in/alecthomas/kingpin.v3-unstable imports
	github.com/nicksnyder/go-i18n/i18n: module github.com/nicksnyder/go-i18n@latest (v2.0.2+incompatible) found, but does not contain package github.com/nicksnyder/go-i18n/i18n

```
This does not exist -> github.com/nicksnyder/go-i18n/i18n
It has been changed to github.com/nicksnyder/go-i18n/v2/i18n

**Comment by terryding77** [comment]
as trick, I forked this package and remove `github.com/alecthomas/gometalinter` at **tools.go** file in this [commit](https://github.com/terryding77/promptui/commit/7bbda0157b3cfebcce1214030934a8604d506390)
now  I can add 
```
replace github.com/manifoldco/promptui => github.com/terryding77/promptui v0.3.3
```
into **go.mod** to avoid problem with golang 1.13

I know this solution is not a great way, as getting the official solution, I well delete the fork repo. 
we hope this problem can be fixed as soon as possible!

**Comment by nervo** [comment]
@terryding77 what about just adding `replace github.com/nicksnyder/go-i18n => github.com/nicksnyder/go-i18n v1.10.1` in your own `go.mod` ?

Btw, @jbowes the problem still occurs, maybe the issue should be re-open :)

**Comment by jbowes** [comment]
Ok, we've got a real proper solution now on master. I'll be tagging shortly. No more replaces needed!
