### ISSUE TITLE
Prompt resource doesn't remove cursor when ENTER key is pressed.

### ISSUE THREAD

**Issue by richardmcsong** [manifoldco/promptui#117]
![image](https://user-images.githubusercontent.com/9144514/69073552-a51ffe00-09fb-11ea-9213-f615b7fe9774.png)
Code:
```
prompt = promptui.Prompt{
	Label: "Prompt 3",
}
_, err = prompt.Run()
```

The string that I get back from prompt.Run doesn't include the cursor, though.

**Comment by chriszzt** [comment]
You could try my fork. I fixed it some way.
Since it is a bit hack, I might not create pr to really fix it for now.
https://github.com/tigergraph/promptui

**Comment by laverya** [comment]
Is the issue just that the length in bytes is different than the length in runes then @chriszzt? Assuming https://github.com/tigergraph/promptui/pull/2/files is the relevant PR and not https://github.com/tigergraph/promptui/pull/1/files, I mean - since 1 was much larger than 2

**Comment by chriszzt** [comment]
> https://github.com/tigergraph/promptui/pull/2/files

Oh, actually `c.input` is of type []rune, that is why i delete unnecessary type conversion in my pr

**Comment by jamesdobson** [comment]
Created PR #147 which extracts the commit PR #118 by @richardmcsong that deals specifically with this issue (PR #118 also contains additional functionality), hopefully making PR #147 easier to accept.

Also, PR #147 does pass the CI build, which also hopefully makes it easier to accept.
