### ISSUE TITLE
Ctrl-H support to delete input text

### ISSUE THREAD

**Issue by micnncim** [manifoldco/promptui#136]
Currently, <kbd>Ctrl</kbd>+<kbd>H</kbd> is unavailable to delete input text. It will be good for some users to support <kbd>Ctrl</kbd>+<kbd>H</kbd>.

I rather want this feature. See also: https://github.com/manifoldco/promptui/pull/135.

**Comment by bcongdon** [comment]
This looks like it is now fixed.
