### ISSUE TITLE
Put cursor at the end of the line when providing default value

### ISSUE THREAD

**Issue by bsinou** [manifoldco/promptui#146]
With latest version (0.7.0) when running the prompt_default example from the `_examples` package, the cursor is placed over the first letter of the provided default value.

```sh
user@focal:~/dev/sandbox/prompt_default$ go run main.go   
✔ Username: █ser
```  

Is it possible to rather place the cursor after last character (at the end of the line) by default? 
I had a look at the various available options and I have not found a way to do it.

By the way, many thanks for this tool!

**Comment by skmatz** [comment]
@bsinou

Add `AllowEdit: true` to your `promptui.Prompt`.

**Comment by bsinou** [comment]
@skmatz 

Well... It works like a charm. 
Thanks for the tip.
