### ISSUE TITLE
Feature: Allow checkbox in select

### ISSUE THREAD

**Issue by rubiin** [manifoldco/promptui#156]
So I am building a cli which allows user to select multiple items and run some operation on them. How can we achieve this ?

**Comment by chriswalz** [comment]
I'm also interested in this

**Comment by ahume** [comment]
I've put together a spike of this, to prove the basic concept.

![multi-select](https://user-images.githubusercontent.com/30920/99890901-f04a9d80-2c5b-11eb-8395-ba723704d679.gif)

Is there interest in adding this feature in principal? Or is this best left in our own fork?

```
package main

import (
	"fmt"

	"github.com/manifoldco/promptui"
)

func main() {
	prompt := promptui.MultiSelect{
		Label: "Select Day",
		Items: []string{"Monday", "Tuesday", "Wednesday", "Thursday", "Friday",
			"Saturday", "Sunday"},
	}

	_, result, err := prompt.Run()

	if err != nil {
		fmt.Printf("Prompt failed %v\n", err)
		return
	}

	fmt.Printf("You chose %q\n", result)
}
```

**Comment by IsQiao** [comment]
this is alternative
https://github.com/AlecAivazis/survey

**Comment by rubiin** [comment]
> this is alternative
> https://github.com/AlecAivazis/survey

that looks way better for my project
