### ISSUE TITLE
License issue: dependencies are LGPL'ed

### ISSUE THREAD

**Issue by evanmoses-okta** [manifoldco/promptui#189]
Hi, I'd love to use your library, it's very nicely done, but some of your transitive dependencies (specifically `juju/ansiterm`) are licensed under the LGPL, and that means I can't use it in my product.  The LGPL specifically requires that libraries be dynamically linked to not "infect" applications that depend on them (that is, if you statically link against a LGPL'ed library, you must license the entire app with the LGPL).  This probably affects your library as well, IANAL but you may be in violation of that license.  

It looks like this library may be a more permissively-licensed alternative: https://github.com/logrusorgru/aurora

**Comment by arbourd** [comment]
#181

**Comment by evanmoses-okta** [comment]
@arbourd thanks, closing this as a duplicate.
