### ISSUE TITLE
backspace not working on windows.

### ISSUE THREAD

**Issue by KaelBaldwin** [manifoldco/promptui#31]
This might have more to do with one of the underlying dependencies, but on windows 10 backspace is not working for me when using Prompt.Run()

Here's how I'm using it:
```
// This is within a loop with a new field on each iteration.

prompt := promptui.Prompt{
    Label: field,
}

result, err := prompt.Run()
if err != nil {
	panic(err)
}
```

**Comment by AlecAivazis** [comment]
@KaelBaldwin  - I hope @luizbranco doesn't mind me sharing another project (please delete this comment if so!) but I have been working on a very similar package that has full windows support which might be able to hold you over until prompt-ui has better support for windows: https://github.com/AlecAivazis/survey

**Comment by meinstein** [comment]
@KaelBaldwin I ran into the same issue and ended up going with [AlecAivazis/survey](http://github.com/AlecAivazis/survey) which seemed to have a lot better windows support

**Comment by KaelBaldwin** [comment]
Thanks @meinstein

**Comment by luizbranco** [comment]
@KaelBaldwin that should fix the issue: https://github.com/manifoldco/promptui/pull/37

**Comment by KaelBaldwin** [comment]
thanks! trying it out now!

**Comment by KaelBaldwin** [comment]
that works! @luizbranco thanks again!

**Comment by luizbranco** [comment]
@KaelBaldwin sorry for the delay. It is now on master.
@meinstein thanks for sharing the link, seems to be a very cool lib. I will take a look
