### ISSUE TITLE
Customized background support

### ISSUE THREAD

**Issue by TimothyYe** [manifoldco/promptui#35]
Hello, this tool is awesome!
Do you have a plan to support the customized background color for select templates? 
For example, support customized background color for active, inactive, selected items, etc.

**Comment by luizbranco** [comment]
@TimothyYe do you mean the text background or the entire line? If the former, you can check this PR: https://github.com/manifoldco/promptui/pull/36

Eg: `Active:   "{{ .Name | white | bgRed }}"`

Adding color to the entire line is a bit more complicated. As far as I know, we would need to fill the size of the screen with spaces.

**Comment by TimothyYe** [comment]
Yes, I mean the background color for the entire line.

**Comment by TimothyYe** [comment]
Hi, just reviewed that PR, I think the text background is what I want.

**Comment by TimothyYe** [comment]
Waiting for that PR to be merged :-)

**Comment by luizbranco** [comment]
Awesome, just merged!

**Comment by TimothyYe** [comment]
Thanks!
