### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by phifty** [manifoldco/promptui#46]
I'm getting a compile error if I try version 0.2.1:

    github.com/manifoldco/promptui/prompt.go:88:11: cannot use p.stdin (type io.Reader) as type io.ReadCloser in assignment:
	io.Reader does not implement io.ReadCloser (missing Close method)

**Comment by sethusrinivasan** [comment]
I tried following sample in https://hackernoon.com/improve-your-command-line-go-application-with-promptui-258ebe9eed1

am facing same issue, 

go get -u github.com/manifoldco/promptui
# github.com/manifoldco/promptui
../../../../go/src/github.com/manifoldco/promptui/prompt.go:88:11: cannot use p.stdin (type io.Reader) as type io.ReadCloser in assignment:
	io.Reader does not implement io.ReadCloser (missing Close method)
