### ISSUE TITLE
Problem with types in prompt.go

### ISSUE THREAD

**Issue by jasiu001** [manifoldco/promptui#62]
Hi,

I try to run basic examples on Mac, golang version 1.10. I got an error:
`vendor/github.com/manifoldco/promptui/prompt.go:88:11: cannot use p.stdin (type io.Reader) as type io.ReadCloser in assignment:
	io.Reader does not implement io.ReadCloser (missing Close method)`
When I comment this line it works fine.

**Comment by hallazzang** [comment]
This problem occurs frequently, try to fetch the latest version(`master` branch)

**Comment by warren-veerasingam** [comment]
I am facing the same issue. My tests are failing. When would this be released?

**Comment by luizbranco** [comment]
Sorry for the delay, everyone. There is a new release fixing this issue: https://github.com/manifoldco/promptui/releases/tag/v0.3.0

Please re-open if you are still experiencing the problem.
