### ISSUE TITLE
Cursor character modification suggestions

### ISSUE THREAD

**Issue by mritd** [manifoldco/promptui#65]
It is recommended to change the cursor character to `\u258D`；Screenshot of the mac terminal under the cursor does not look good.

![image](https://user-images.githubusercontent.com/13043245/37099508-6d9a8efc-225b-11e8-998a-9064114169dc.png)
![image](https://user-images.githubusercontent.com/13043245/37099558-914932b8-225b-11e8-9967-dda08a98b809.png)

**Comment by chenhg5** [comment]
@mritd im facing the same problem, do you have any solutions?
