### ISSUE TITLE
Go get compiler error with screenbuf.go

### ISSUE THREAD

**Issue by papagunit** [manifoldco/promptui#69]
Promptui is being pulled in as a dependency within another project when using go get. I get the following:

```
# github.com/manifoldco/promptui/screenbuf
src/github.com/manifoldco/promptui/screenbuf/screenbuf.go:46: undefined: bytes.ContainsAny
```

Please advise.

**Comment by jbowes** [comment]
hi @papagunit!

Go added `bytes.ContainsAny` to the standard library in 1.7. You're probably using an old version of Go. I'd suggest upgrading; Go 1.7 itself is almost 2 years old :)

Hope that helps!

**Comment by papagunit** [comment]
Go figure, default version for the ubuntu ppa is 1.6, that's no good. Just an fyi for anyone else who might come across this. Thanks!
