### ISSUE TITLE
Success template in Prompt is never rendered

### ISSUE THREAD

**Issue by hassansin** [manifoldco/promptui#70]
I'm not sure if this is intended or not but the `Success` template  in `PromptTemplates` is never rendered. I tried the `custom_prompt` example and had the same behavior.

I think in this [line](https://github.com/manifoldco/promptui/blob/master/prompt.go#L231) we could render `success` template instead. I can send a PR if you agree.

Thanks for this really cool package!

**Comment by Minivera** [comment]
This was fixed in #71, thanks for the contribution!
