### ISSUE TITLE
Hide help message

### ISSUE THREAD

**Issue by laverboy** [manifoldco/promptui#83]
There seems to be no way of suppressing the help message in a select template.

If you set the help message to blank string "", then it defaults to 'Use the arrow keys to navigate'. As per (in select.go):

    if tpls.Help == "" {
		tpls.Help = fmt.Sprintf(`{{ "Use the arrow keys to navigate:" | faint }} {{ .NextKey | faint }} ` +
			`{{ .PrevKey | faint }} {{ .PageDownKey | faint }} {{ .PageUpKey | faint }} ` +
			`{{ if .Search }} {{ "and" | faint }} {{ .SearchKey | faint }} {{ "toggles search" | faint }}{{ end }}`)
	}

Have I missed something? Thanks

**Comment by royeo** [comment]
I submitted a PR #87 to support this feature.

**Comment by enmand** [comment]
Closed with https://github.com/manifoldco/promptui/pull/87

**Comment by drgrib** [comment]
Not sure if this is documented somewhere but if someone wants to use this feature it is now found through setting `HideHelp` like this:

``` go
prompt := promptui.Select{
	Label:    "Are you sure you want to proceed",
	Items:    []string{"Yes", "No"},
	HideHelp: true,
}
```
